# Numpy

In [1]:
import numpy as np

Gerar array

In [11]:
np1 = np.array(range(1,10))

In [12]:
np1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(np1)

numpy.ndarray

In [6]:
np2 = np.array([[1,2,3],[4,5,6]])

In [7]:
np2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(np2)

numpy.ndarray

In [9]:
np2.shape

(2, 3)

In [13]:
np1.shape

(9,)

In [15]:
np3 = np.array([1,"Two"])

In [16]:
np3.dtype

dtype('<U11')

In [17]:
np3[0]

'1'

In [18]:
np3[1] = 2

In [20]:
np3

array(['1', '2'], dtype='<U11')

In [21]:
np2.dtype

dtype('int32')

In [22]:
np2[0,0] = "String"

ValueError: invalid literal for int() with base 10: 'String'

In [23]:
np4 = np.array([["1",2],[3,4]])

In [24]:
np4

array([['1', '2'],
       ['3', '4']], dtype='<U1')

In [25]:
np4.dtype

dtype('<U1')

In [26]:
np4[0,0] = 0

In [27]:
np4.dtype

dtype('<U1')

In [29]:
np5 = np.arange(0,10)
np5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np6 = np.linspace(0,10,10)

In [33]:
np6

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [35]:
np7 = np.random.rand(5,5)
np7

array([[0.89570374, 0.11739788, 0.11478192, 0.39005002, 0.1257141 ],
       [0.19666551, 0.97255318, 0.518069  , 0.63643307, 0.93126629],
       [0.56447155, 0.34411795, 0.14361019, 0.64961469, 0.28145704],
       [0.96725623, 0.4885883 , 0.08242589, 0.5385343 , 0.98852202],
       [0.01025688, 0.6067154 , 0.18431163, 0.75828365, 0.65011892]])

* np.diag
* np.zeros
* np.ones

In [41]:
help(np.diag)

Help on function diag in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input 

In [42]:
np.diag(np2, 0)

array([1, 5])

In [43]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [44]:
np.zeros(1)

array([0.])

In [46]:
np.zeros([5,1])

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [47]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [48]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])